{{- if not .Values.jira.apiTokenFromSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jira.fullname" . }}-secret
data:
   jiraApiToken: {{ .Values.jira.apiToken | b64enc }}
type: Opaque
{{- end }}
