teleport:
  nodename: luna.teleport
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
auth_service:
  cluster_name: teleport  
  enabled: "yes"
ssh_service:
  enabled: "yes"
  labels:
    env: example
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  # The DNS name of the proxy
  public_addr: ["proxy.luna.teleport:443"]
  # Web listen host:port
  web_listen_addr: "0.0.0.0:443"
