{{- if not .Values.mattermost.tokenFromSecret -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "mattermost.fullname" . }}-secret
data:
  mattermostToken: {{ .Values.mattermost.token | b64enc }}
{{- end }}
