{{- if not .Values.pagerduty.apiKeyFromSecret -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "pagerduty.fullname" . }}-secret
data:
  pagerdutyApiKey: {{ .Values.pagerduty.apiKey | b64enc }}
{{- end }}
