kind: role
version: v3
metadata:
  name: bot
spec:
  # SSH options used for user sessions 
  options:
    # max_session_ttl defines the TTL (time to live) of SSH certificates 
    # issued to the users with this role.
    max_session_ttl: 10h

  # allow section declares a list of resource/verb combinations that are
  # allowed for the users of this role. by default nothing is allowed.
  allow:
    logins: ['root']
    node_labels:
      '*': '*'
---
kind: user
version: v2
metadata:
  name: bot
spec:
  roles: ['bot']
---  
kind: user
version: v2
metadata:
  name: editor
spec:
  roles: ['editor', 'access']
