{{- if not .Values.discord.tokenFromSecret -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "discord.fullname" . }}-secret
data:
   discordToken: {{ .Values.discord.token | b64enc }}
{{- end }}
