name: Unit Tests (Rust)
run-name: Unit Tests (Rust) - ${{ github.run_id }} - @${{ github.actor }}

on:
  pull_request:
    paths:
      - '.github/workflows/unit-tests-rust.yaml'
      - '**.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'build.assets/Makefile'
      - 'build.assets/Dockerfile*'
      - 'Makefile'
  merge_group:
    paths:
      - '.github/workflows/unit-tests-rust.yaml'
      - '**.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'build.assets/Makefile'
      - 'build.assets/Dockerfile*'
      - 'Makefile'

jobs:
  test:
    name: Unit Tests (Rust)
    if: ${{ !startsWith(github.head_ref, 'dependabot/') }}
    runs-on: ubuntu-latest

    permissions:
      contents: read

    container:
      image: ghcr.io/gravitational/teleport-buildbox:teleport15
      options: --cap-add=SYS_ADMIN --privileged

    steps:
      - name: Checkout Teleport
        uses: actions/checkout@v4

      - name: Run tests
        timeout-minutes: 40
        run: make test-rust
